# Generated by Django 5.2.4 on 2025-07-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('sector', models.CharField(default='N/A', max_length=100)),
                ('price_change', models.FloatField()),
                ('rsi', models.FloatField(default=50.0)),
                ('volume', models.CharField(default='N/A', max_length=20)),
                ('market_cap', models.CharField(default='N/A', max_length=20)),
                ('is_positive', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-price_change'],
            },
        ),
    ]
